# Write your MySQL query statement below
SELECT ID,
MAX(CASE WHEN MONTH = "JAN" THEN REVENUE ELSE NULL END) AS JAN_REVENUE,
MAX(CASE WHEN MONTH = "FEB" THEN REVENUE ELSE NULL END) AS FEB_REVENUE,
MAX(CASE WHEN MONTH = "MAR" THEN REVENUE ELSE NULL END) AS MAR_REVENUE,
MAX(CASE WHEN MONTH = "APR" THEN REVENUE ELSE NULL END) AS APR_REVENUE,
MAX(CASE WHEN MONTH = "MAY" THEN REVENUE ELSE NULL END) AS MAY_REVENUE,
MAX(CASE WHEN MONTH = "JUN" THEN REVENUE ELSE NULL END) AS JUN_REVENUE,
MAX(CASE WHEN MONTH = "JUL" THEN REVENUE ELSE NULL END) AS JUL_REVENUE,
MAX(CASE WHEN MONTH = "AUG" THEN REVENUE ELSE NULL END) AS AUG_REVENUE,
MAX(CASE WHEN MONTH = "SEP" THEN REVENUE ELSE NULL END) AS SEP_REVENUE,
MAX(CASE WHEN MONTH = "OCT" THEN REVENUE ELSE NULL END) AS OCT_REVENUE,
MAX(CASE WHEN MONTH = "NOV" THEN REVENUE ELSE NULL END) AS NOV_REVENUE,
MAX(CASE WHEN MONTH = "DEC" THEN REVENUE ELSE NULL END) AS DEC_REVENUE
FROM DEPARTMENT GROUP BY ID;

